[package]
name = "joshu/rologger"
description = "Lightweight logging module for Roblox"
version = "0.1.4"
license = "GNU GPLv3"
authors = ["Josh Roberts <joshua.roberts@gamefam.com>"]
realm = "shared"
registry = "https://github.com/notjoshno/wally-index"

[dependencies]
